name: Accessibility tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers and system deps
        run: npx playwright install --with-deps

      - name: Run accessibility tests
        run: npx playwright test a11y-region.spec.js --reporter=junit

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
